### ISSUE TITLE
Doesn't work with latest pandas 0.20.1 and 0.20.2

### ISSUE THREAD

**Issue by arliber** [martin-gorner/tensorflow-mnist-tutorial#50]
Failed with the error:

`'pandas' has no attribute 'computation'`

Had to downgrade to pandas 0.20.0 like that:

`pip install 'pandas==0.20.' --force-reinstall`

Hope that helps someone

**Comment by EngFawadKhan** [comment]
Bro you solved my problem. I can't thank you enough. I hope you excel in your career.

**Comment by EngFawadKhan** [comment]
I will elaborate on my problem to help anyone else:

If you are receiving this kind of error:

![image](https://user-images.githubusercontent.com/29304460/27005157-0b4061da-4e32-11e7-8453-e49c5b604ff8.png)

copy and paste the below line of code in your CMD:

`pip install pandas==0.20. --force-reinstall`

I also had to upgrade my numpy to 1.13.0 using

`pip install --upgrade numpy`

I am not sure about this line of code so plz search it in google to get the right syntex.

I am using python3

**Comment by EngFawadKhan** [comment]
It sucks that upgrading libs causes these kinds of error.

**Comment by martin-gorner** [comment]
Closing since this sample does not use pandas in any way.
